/* Parser.java */
/* Generated By:JavaCC: Do not edit this line. Parser.java */
package de.lathanda.eos.parser.de;
import de.lathanda.eos.parser.base.*;
import de.lathanda.eos.parser.core.*;
import de.lathanda.eos.vm.*;
import de.lathanda.eos.base.*;
import de.lathanda.eos.base.MutableColor;
import java.io.File;
import java.io.IOException;
@SuppressWarnings("unused")
public class Parser implements ParserConstants {
    private MarkerStack markerStack = new MarkerStack();
    private Program program;
    private String path;
    private int level;
    void open() {
        markerStack.push(new Marker());
        Token old = token;
        getNextToken();
        markerStack.peek().begin(token.beginColumn, token.beginLine);
        token = old;
    }
    void close(MarkedNode node) {
        markerStack.peek().end(token.endColumn, token.endLine);
        node.setMarker(markerStack.pop());
        program.addNode(node);
    }
    void setCode(MarkedNode node) {
        node.setMarker(new Marker(token.beginColumn, token.beginLine, token.endColumn, token.endLine));
        program.addNode(node);
    }
    void newlineInc() {
        Token old = token;
        program.prettyPrinterNewline(getNextToken().beginColumn, level);
        level++;
        token = old;
    }
    void newlineDec() {
        Token old = token;
        level--;
        program.prettyPrinterNewline(getNextToken().beginColumn, level);
        token = old;
    }
    void newlineDecInc() {
        Token old = token;
        level--;
        program.prettyPrinterNewline(getNextToken().beginColumn, level);
        level++;
        token = old;
    }
    void newline() {
        Token old = token;
        program.prettyPrinterNewline(getNextToken().beginColumn, level);
        token = old;
    }

/** Produktionen */
  final public void Parse(Program program, String path) throws ParseException {this.path = path;
  this.program = program;
  token_source.setProgram(program);
  Sequence sequence;
  SubRoutine sub;
  UserClass cls;
    sequence = Sequence();
program.add(sequence);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IMPORT:
      case PROGRAM:
      case PROCEDURE:
      case METHOD:
      case CLASS:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PROGRAM:{
        sequence = Program();
program.add(sequence);
        break;
        }
      case PROCEDURE:{
        sub = Procedure();
program.add(sub);
        break;
        }
      case METHOD:{
        sub = Method();
program.add(sub);
        break;
        }
      case CLASS:{
        cls = UserClass();
program.add(cls);
        break;
        }
      case IMPORT:{
        Import();
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      sequence = Sequence();
program.add(sequence);
    }
    jj_consume_token(0);
}

  final public Sequence Program() throws ParseException {Sequence sequence;
newlineInc();
    jj_consume_token(PROGRAM);
    sequence = Sequence();
newlineDec();
    jj_consume_token(END_PROGRAM);
{if ("" != null) return sequence;}
    throw new Error("Missing return statement in function");
}

  final public SubRoutine Procedure() throws ParseException {String name; Sequence sequence;Parameters parameters = null; Type ret =null;
open();
newlineInc();
    jj_consume_token(PROCEDURE);
    name = Name();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LPAREN:{
      parameters = Parameters();
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case COLON:{
      jj_consume_token(COLON);
      ret = Type();
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      ;
    }
    sequence = Sequence();
newlineDec();
    jj_consume_token(END_PROCEDURE);
SubRoutine subroutine = new SubRoutine(name, parameters, sequence, ret, false);
    close(subroutine);
    {if ("" != null) return subroutine;}
    throw new Error("Missing return statement in function");
}

  final public UserClass UserClass() throws ParseException {String name; String sup = null; UserClass cls; Method meth; Property prop;Sequence sequence;
open();
newlineInc();
    jj_consume_token(CLASS);
    name = Name();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case EXTENDS:{
      jj_consume_token(EXTENDS);
      sup = Name();
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      ;
    }
cls = program.createUserClass(name); cls.setSuperClass(sup);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case METHOD:
      case IDENTIFIER:{
        ;
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        break label_2;
      }
newline();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case METHOD:{
        meth = UserMethod(cls);
cls.addMethod(meth);
        break;
        }
      case IDENTIFIER:{
        prop = UserProperty(cls);
cls.addProperty(prop);
        break;
        }
      default:
        jj_la1[6] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
newlineDec();
    jj_consume_token(END_CLASS);
close(cls);
    {if ("" != null) return cls;}
    throw new Error("Missing return statement in function");
}

  final public Method UserMethod(UserClass ut) throws ParseException {String name; Sequence sequence;Parameters parameters = null; Type ret =null;
open();
newlineInc();
    jj_consume_token(METHOD);
    name = Name();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LPAREN:{
      parameters = Parameters();
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case COLON:{
      jj_consume_token(COLON);
      ret = Type();
      break;
      }
    default:
      jj_la1[8] = jj_gen;
      ;
    }
    sequence = Sequence();
newlineDec();
    jj_consume_token(END_METHOD);
Method method = new Method(name, parameters, sequence, ret, ut);
    close(method);
    {if ("" != null) return method;}
    throw new Error("Missing return statement in function");
}

  final public Property UserProperty(UserClass ut) throws ParseException {String name;
  Type type;
  Property property = new Property(ut);
    name = Name();
property.addName(name);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SEPARATOR:{
        ;
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        break label_3;
      }
      jj_consume_token(SEPARATOR);
      name = Name();
property.addName(name);
    }
    jj_consume_token(COLON);
    type = Type();
property.setType(type);
{if ("" != null) return property;}
    throw new Error("Missing return statement in function");
}

  final public SubRoutine Method() throws ParseException {String name; Sequence sequence;Parameters parameters = null; Type ret =null;
open();
newlineInc();
    jj_consume_token(METHOD);
    name = Name();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LPAREN:{
      parameters = Parameters();
      break;
      }
    default:
      jj_la1[10] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case COLON:{
      jj_consume_token(COLON);
      ret = Type();
      break;
      }
    default:
      jj_la1[11] = jj_gen;
      ;
    }
    sequence = Sequence();
newlineDec();
    jj_consume_token(END_METHOD);
SubRoutine subroutine = new SubRoutine(name, parameters, sequence, ret, true);
    close(subroutine);
    {if ("" != null) return subroutine;}
    throw new Error("Missing return statement in function");
}

  final public Parameters Parameters() throws ParseException {Parameters parameters = new Parameters();
    jj_consume_token(LPAREN);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFIER:{
      Parameter(parameters);
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case SEPARATOR:{
          ;
          break;
          }
        default:
          jj_la1[12] = jj_gen;
          break label_4;
        }
        jj_consume_token(SEPARATOR);
        Parameter(parameters);
      }
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      ;
    }
    jj_consume_token(RPAREN);
{if ("" != null) return parameters;}
    throw new Error("Missing return statement in function");
}

  final public void Parameter(Parameters parameters) throws ParseException {String name; Type type;
    name = Name();
parameters.addName(name);
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SEPARATOR:{
        ;
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        break label_5;
      }
      jj_consume_token(SEPARATOR);
      name = Name();
parameters.addName(name);
    }
    jj_consume_token(COLON);
    type = Type();
parameters.setType(type, new Marker(token.beginColumn, token.beginLine, token.endColumn, token.endLine));
}

  final public void Import() throws ParseException {File file;
  Program subprogram;
newlineInc();
    jj_consume_token(IMPORT);
    file = File();
try {
        subprogram = new Program(program);
        Parser parser = new Parser(new StringCharStream(file));
        parser.Parse(subprogram, file.getParent());
        program.merge(subprogram, new Marker(token.beginColumn, token.beginLine, token.endColumn, token.endLine));
      } catch (IOException ioe) {
        {if (true) throw new ParseException(ioe.getLocalizedMessage());}
      }
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SEPARATOR:{
        ;
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        break label_6;
      }
      jj_consume_token(SEPARATOR);
newline();
      file = File();
try {
          subprogram = new Program(program);
          Parser parser = new Parser(new StringCharStream(file));
          parser.Parse(subprogram, file.getParent());
          program.merge(subprogram, new Marker(token.beginColumn, token.beginLine, token.endColumn, token.endLine));
        } catch (IOException ioe) {
          {if (true) throw new ParseException(ioe.getLocalizedMessage());}
        }
    }
newlineDec();
    jj_consume_token(END_IMPORT);
}

  final public Sequence Sequence() throws ParseException {Sequence sequence = new Sequence();
  Node instruction;
  open();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case REPEAT:
      case IF:
      case WITH:
      case SELF:
      case WHILE:
      case RESULT:
      case BREAKPOINT:
      case STOP:
      case IDENTIFIER:{
        ;
        break;
        }
      default:
        jj_la1[16] = jj_gen;
        break label_7;
      }
open();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case REPEAT:
      case WHILE:{
        instruction = Loop();
        break;
        }
      case IF:{
        instruction = IfElse();
        break;
        }
      case WITH:{
        instruction = With();
        break;
        }
      case SELF:
      case RESULT:
      case BREAKPOINT:
      case STOP:
      case IDENTIFIER:{
        instruction = Statement();
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
close(instruction);
    sequence.append(instruction);
    }
close(sequence);
    {if ("" != null) return sequence;}
    throw new Error("Missing return statement in function");
}

  final public Node Loop() throws ParseException {Node loop;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case REPEAT:{
newlineInc();
      jj_consume_token(REPEAT);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case FOREVER:{
        loop = RepeatForever();
        break;
        }
      case UNTIL:{
        loop = RepeatUntil();
        break;
        }
      default:
        jj_la1[18] = jj_gen;
        if (jj_2_1(2147483647)) {
          //Langsamere korrekte Erkennung
              loop = RepeatPreWhile();
        } else if (jj_2_2(2147483647)) {
          loop = RepeatTimes();
        } else {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case REPEAT:
          case END_REPEAT:
          case IF:
          case WITH:
          case SELF:
          case WHILE:
          case RESULT:
          case BREAKPOINT:
          case STOP:
          case IDENTIFIER:{
            loop = RepeatPostWhile();
            break;
            }
          default:
            jj_la1[19] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
      }
      break;
      }
    case WHILE:{
      loop = WhileDo();
      break;
      }
    default:
      jj_la1[20] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return loop;}
    throw new Error("Missing return statement in function");
}

  final public IfElse IfElse() throws ParseException {Sequence a;
  Sequence b = null;
  Expression expression;
newlineInc();
    jj_consume_token(IF);
    expression = Expression();
    jj_consume_token(THEN);
    a = Sequence();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ELSE:{
newlineDecInc();
      jj_consume_token(ELSE);
      b = Sequence();
      break;
      }
    default:
      jj_la1[21] = jj_gen;
      ;
    }
newlineDec();
    jj_consume_token(END_IF);
{if ("" != null) return new IfElse(expression,a,b);}
    throw new Error("Missing return statement in function");
}

  final public With With() throws ParseException {Expression with;
  Sequence sequence;
newlineInc();
    jj_consume_token(WITH);
    with = Expression();
    sequence = Sequence();
newlineDec();
    jj_consume_token(END_WITH);
{if ("" != null) return new With(with, sequence);}
    throw new Error("Missing return statement in function");
}

  final public RepeatForever RepeatForever() throws ParseException {Sequence sequence;
    jj_consume_token(FOREVER);
    sequence = Sequence();
newlineDec();
    jj_consume_token(END_REPEAT);
{if ("" != null) return new RepeatForever(sequence);}
    throw new Error("Missing return statement in function");
}

  final public RepeatTimes RepeatTimes() throws ParseException {Sequence sequence;
  Expression times = null;
    times = Expression();
setCode(times);
    jj_consume_token(TIMES);
    sequence = Sequence();
newlineDec();
    jj_consume_token(END_REPEAT);
{if ("" != null) return new RepeatTimes(times, sequence);}
    throw new Error("Missing return statement in function");
}

  final public WhileDo RepeatUntil() throws ParseException {Expression expression;
  Expression not;
  Sequence sequence;
    jj_consume_token(UNTIL);
    expression = Expression();
    sequence = Sequence();
newlineDec();
    jj_consume_token(END_REPEAT);
not = expression.not();
    not.sameMarker(expression);
    {if ("" != null) return new WhileDo(not, sequence);}
    throw new Error("Missing return statement in function");
}

  final public WhileDo RepeatPreWhile() throws ParseException {Expression expression;
  Sequence sequence;
    jj_consume_token(WHILE);
    expression = Expression();
    sequence = Sequence();
newlineDec();
    jj_consume_token(END_REPEAT);
{if ("" != null) return new WhileDo(expression, sequence);}
    throw new Error("Missing return statement in function");
}

  final public DoWhile RepeatPostWhile() throws ParseException {Expression expression;
  Sequence sequence;
    sequence = Sequence();
newlineDec();
    jj_consume_token(END_REPEAT);
    jj_consume_token(WHILE);
    expression = Expression();
{if ("" != null) return new DoWhile(sequence, expression);}
    throw new Error("Missing return statement in function");
}

  final public WhileDo WhileDo() throws ParseException {Expression expression;
  Sequence sequence;
newlineInc();
    jj_consume_token(WHILE);
    expression = Expression();
    jj_consume_token(DO);
    sequence = Sequence();
newlineDec();
    jj_consume_token(END_WHILE);
{if ("" != null) return new WhileDo(expression, sequence);}
    throw new Error("Missing return statement in function");
}

  final public Node Statement() throws ParseException {Node statement;
newline();
    if (jj_2_3(2)) {
      statement = Declaration();
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SELF:
      case RESULT:
      case IDENTIFIER:{
        statement = Command(null);
        break;
        }
      case BREAKPOINT:{
        statement = Breakpoint();
        break;
        }
      case STOP:{
        statement = Stop();
        break;
        }
      default:
        jj_la1[22] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return statement;}
    throw new Error("Missing return statement in function");
}

  final public Node Breakpoint() throws ParseException {
    jj_consume_token(BREAKPOINT);
{if ("" != null) return new Breakpoint();}
    throw new Error("Missing return statement in function");
}

  final public Node Stop() throws ParseException {
    jj_consume_token(STOP);
{if ("" != null) return new Stoppoint();}
    throw new Error("Missing return statement in function");
}

  final public Declaration Declaration() throws ParseException {String name;
  Type type;
  Declaration declaration = new Declaration();
    name = Name();
declaration.addName(name);
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SEPARATOR:{
        ;
        break;
        }
      default:
        jj_la1[23] = jj_gen;
        break label_8;
      }
      jj_consume_token(SEPARATOR);
      name = Name();
declaration.addName(name);
    }
    jj_consume_token(COLON);
    type = Type();
declaration.setType(type);
{if ("" != null) return declaration;}
    throw new Error("Missing return statement in function");
}

  final public Node Command(Expression left) throws ParseException {Expression expression;
  Node command = null;
    if (jj_2_4(2)) {
      expression = Function(left);
{if ("" != null) return expression;}
    } else if (jj_2_5(2)) {
      command = Assignment(left);
{if ("" != null) return command;}
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SELF:
      case RESULT:
      case IDENTIFIER:{
        expression = PropertyRead(left);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case DOT:{
          jj_consume_token(DOT);
          command = Command(expression);
          break;
          }
        default:
          jj_la1[24] = jj_gen;
          ;
        }
if (command != null) {
      {if ("" != null) return command;}
    } else {
      {if ("" != null) return expression;}
    }
        break;
        }
      default:
        jj_la1[25] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
}

  final public Assignment Assignment(Expression left) throws ParseException {PropertyWrite property;
  Expression expression;
    property = PropertyWrite(left);
    AssignmentOperator();
    expression = Expression();
{if ("" != null) return new Assignment(property, expression);}
    throw new Error("Missing return statement in function");
}

  final public void AssignmentOperator() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case EQ:{
      jj_consume_token(EQ);
      break;
      }
    case ASSIGN:{
      jj_consume_token(ASSIGN);
      break;
      }
    default:
      jj_la1[26] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public Expression Expression() throws ParseException {Expression expression; Expression b; open();
    expression = AndExpression();
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OR:{
        ;
        break;
        }
      default:
        jj_la1[27] = jj_gen;
        break label_9;
      }
      jj_consume_token(OR);
      b = AndExpression();
close(expression);open();expression = expression.or(b);
    }
close(expression);
    {if ("" != null) return expression;}
    throw new Error("Missing return statement in function");
}

  final public Expression AndExpression() throws ParseException {Expression expression; Expression b; open();
    expression = EqualityExpression();
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case AND:{
        ;
        break;
        }
      default:
        jj_la1[28] = jj_gen;
        break label_10;
      }
      jj_consume_token(AND);
      b = EqualityExpression();
expression = expression.and(b);
    }
close(expression);
    {if ("" != null) return expression;}
    throw new Error("Missing return statement in function");
}

  final public Expression EqualityExpression() throws ParseException {Expression expression; Expression b; open();
    expression = RelationalExpression();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case EQ:
    case NE:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case EQ:{
        jj_consume_token(EQ);
        b = RelationalExpression();
expression = expression.equals(b);
        break;
        }
      case NE:{
        jj_consume_token(NE);
        b = RelationalExpression();
expression = expression.unequals(b);
        break;
        }
      default:
        jj_la1[29] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[30] = jj_gen;
      ;
    }
close(expression);
    {if ("" != null) return expression;}
    throw new Error("Missing return statement in function");
}

  final public Expression RelationalExpression() throws ParseException {Expression expression; Expression b; open();
    expression = AdditiveExpression();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case GT:
    case LT:
    case LE:
    case GE:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LT:{
        jj_consume_token(LT);
        b = AdditiveExpression();
expression = expression.less(b);
        break;
        }
      case GT:{
        jj_consume_token(GT);
        b = AdditiveExpression();
expression = expression.greater(b);
        break;
        }
      case LE:{
        jj_consume_token(LE);
        b = AdditiveExpression();
expression = expression.lessEquals(b);
        break;
        }
      case GE:{
        jj_consume_token(GE);
        b = AdditiveExpression();
expression = expression.greaterEquals(b);
        break;
        }
      default:
        jj_la1[31] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[32] = jj_gen;
      ;
    }
close(expression);
    {if ("" != null) return expression;}
    throw new Error("Missing return statement in function");
}

  final public Expression AdditiveExpression() throws ParseException {Expression expression; Expression b; open();
    expression = MultiplicativeExpression();
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:
      case MINUS:{
        ;
        break;
        }
      default:
        jj_la1[33] = jj_gen;
        break label_11;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:{
        jj_consume_token(PLUS);
        b = MultiplicativeExpression();
expression = expression.plus(b);
        break;
        }
      case MINUS:{
        jj_consume_token(MINUS);
        b = MultiplicativeExpression();
expression = expression.minus(b);
        break;
        }
      default:
        jj_la1[34] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
close(expression);
    {if ("" != null) return expression;}
    throw new Error("Missing return statement in function");
}

  final public Expression MultiplicativeExpression() throws ParseException {Expression expression; Expression b; open();
    expression = UnaryExpression();
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULT:
      case DIV:{
        ;
        break;
        }
      default:
        jj_la1[35] = jj_gen;
        break label_12;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULT:{
        jj_consume_token(MULT);
        b = UnaryExpression();
expression = expression.multiply(b);
        break;
        }
      case DIV:{
        jj_consume_token(DIV);
        b = UnaryExpression();
expression = expression.divide(b);
        break;
        }
      default:
        jj_la1[36] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
close(expression);
    {if ("" != null) return expression;}
    throw new Error("Missing return statement in function");
}

  final public Expression UnaryExpression() throws ParseException {Expression expression; open();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case MINUS:{
      jj_consume_token(MINUS);
      expression = Pow();
expression = expression.negate();
      break;
      }
    case NOT:{
      jj_consume_token(NOT);
      expression = Pow();
expression = expression.not();
      break;
      }
    case SELF:
    case TRUE:
    case FALSE:
    case RESULT:
    case LPAREN:
    case INTEGER_LITERAL:
    case FLOATING_POINT_LITERAL:
    case STRING_LITERAL1:
    case STRING_LITERAL2:
    case COLOR_LITERAL_RGB:
    case COLOR_LITERAL_RGBA:
    case IDENTIFIER:{
      expression = Pow();
      break;
      }
    default:
      jj_la1[37] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
close(expression);
    {if ("" != null) return expression;}
    throw new Error("Missing return statement in function");
}

  final public Expression Pow() throws ParseException {Expression expression; Expression b; open();
    expression = PrimaryExpression();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case POW:{
      jj_consume_token(POW);
      b = Pow();
expression = expression.pow(b);
      break;
      }
    default:
      jj_la1[38] = jj_gen;
      ;
    }
close(expression);
    {if ("" != null) return expression;}
    throw new Error("Missing return statement in function");
}

  final public Expression PrimaryExpression() throws ParseException {Expression expression; open();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TRUE:
    case FALSE:
    case INTEGER_LITERAL:
    case FLOATING_POINT_LITERAL:
    case STRING_LITERAL1:
    case STRING_LITERAL2:
    case COLOR_LITERAL_RGB:
    case COLOR_LITERAL_RGBA:{
      expression = Literal();
      break;
      }
    default:
      jj_la1[39] = jj_gen;
      if (jj_2_6(2)) {
        expression = Function(null);
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case SELF:
        case RESULT:
        case IDENTIFIER:{
          expression = PropertyRead(null);
          break;
          }
        case LPAREN:{
          jj_consume_token(LPAREN);
          expression = Expression();
          jj_consume_token(RPAREN);
          break;
          }
        default:
          jj_la1[40] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case DOT:{
      expression = PostPrimaryExpression(expression);
      break;
      }
    default:
      jj_la1[41] = jj_gen;
      ;
    }
close(expression);
    {if ("" != null) return expression;}
    throw new Error("Missing return statement in function");
}

  final public Expression PostPrimaryExpression(Expression left) throws ParseException {Expression expression = left;
    label_13:
    while (true) {
      jj_consume_token(DOT);
      if (jj_2_7(2)) {
        expression = Function(expression);
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case SELF:
        case RESULT:
        case IDENTIFIER:{
          expression = PropertyRead(expression);
          break;
          }
        default:
          jj_la1[42] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DOT:{
        ;
        break;
        }
      default:
        jj_la1[43] = jj_gen;
        break label_13;
      }
    }
{if ("" != null) return expression;}
    throw new Error("Missing return statement in function");
}

  final public PropertyRead PropertyRead(Expression left) throws ParseException {String name;
  open();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFIER:{
      name = Name();
      break;
      }
    case RESULT:{
      jj_consume_token(RESULT);
name = ReservedVariables.RESULT;
      break;
      }
    case SELF:{
      jj_consume_token(SELF);
name = ReservedVariables.SELF;
      break;
      }
    default:
      jj_la1[44] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
PropertyRead propertyRead = new PropertyRead(left, name);
    close(propertyRead);
    {if ("" != null) return propertyRead;}
    throw new Error("Missing return statement in function");
}

  final public PropertyWrite PropertyWrite(Expression left) throws ParseException {String name;
  open();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFIER:{
      name = Name();
      break;
      }
    case RESULT:{
      jj_consume_token(RESULT);
name = ReservedVariables.RESULT;
      break;
      }
    default:
      jj_la1[45] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
PropertyWrite propertyWrite = new PropertyWrite(left, name);
    close(propertyWrite);
    {if ("" != null) return propertyWrite;}
    throw new Error("Missing return statement in function");
}

  final public Invoke Function(Expression left) throws ParseException {Arguments args;
  String name;
  open();
    name = Name();
    args = Arguments();
Invoke invoke = new Invoke(left, name, args);
    close(invoke);
    {if ("" != null) return invoke;}
    throw new Error("Missing return statement in function");
}

  final public Arguments Arguments() throws ParseException {Arguments args = new Arguments();
  Expression arg;
    jj_consume_token(LPAREN);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SELF:
    case TRUE:
    case FALSE:
    case RESULT:
    case LPAREN:
    case NOT:
    case MINUS:
    case INTEGER_LITERAL:
    case FLOATING_POINT_LITERAL:
    case STRING_LITERAL1:
    case STRING_LITERAL2:
    case COLOR_LITERAL_RGB:
    case COLOR_LITERAL_RGBA:
    case IDENTIFIER:{
      arg = Expression();
args.append(arg);
      label_14:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case SEPARATOR:{
          ;
          break;
          }
        default:
          jj_la1[46] = jj_gen;
          break label_14;
        }
        jj_consume_token(SEPARATOR);
        arg = Expression();
args.append(arg);
      }
      break;
      }
    default:
      jj_la1[47] = jj_gen;
      ;
    }
    jj_consume_token(RPAREN);
{if ("" != null) return args;}
    throw new Error("Missing return statement in function");
}

  final public Constant Literal() throws ParseException {Constant literal;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INTEGER_LITERAL:{
      literal = IntNumber();
      break;
      }
    case FLOATING_POINT_LITERAL:{
      literal = DoubleNumber();
      break;
      }
    case STRING_LITERAL1:
    case STRING_LITERAL2:{
      literal = Text();
      break;
      }
    case TRUE:
    case FALSE:{
      literal = BooleanLiteral();
      break;
      }
    case COLOR_LITERAL_RGB:
    case COLOR_LITERAL_RGBA:{
      literal = ColorLiteral();
      break;
      }
    default:
      jj_la1[48] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
setCode(literal);
    {if ("" != null) return literal;}
    throw new Error("Missing return statement in function");
}

  final public Constant BooleanLiteral() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TRUE:{
      jj_consume_token(TRUE);
{if ("" != null) return new Constant(Boolean.TRUE,  Type.getBoolean(), "wahr");}
      break;
      }
    case FALSE:{
      jj_consume_token(FALSE);
{if ("" != null) return new Constant(Boolean.FALSE, Type.getBoolean(), "falsch");}
      break;
      }
    default:
      jj_la1[49] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public Constant ColorLiteral() throws ParseException {Token color; MutableColor c; String hex; int r; int g; int b; int a;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case COLOR_LITERAL_RGB:{
      color = jj_consume_token(COLOR_LITERAL_RGB);
hex = color.image;
    r = Integer.parseInt(hex.substring(1,3),16);
    g = Integer.parseInt(hex.substring(3,5),16);
    b = Integer.parseInt(hex.substring(5,7),16);
    c = new MutableColor(r, g, b);
      break;
      }
    case COLOR_LITERAL_RGBA:{
      color = jj_consume_token(COLOR_LITERAL_RGBA);
hex = color.image;
    r = Integer.parseInt(hex.substring(1,3),16);
    g = Integer.parseInt(hex.substring(3,5),16);
    b = Integer.parseInt(hex.substring(5,7),16);
    a = Integer.parseInt(hex.substring(7,9),16);
    c = new MutableColor(r, g, b, a);
      break;
      }
    default:
      jj_la1[50] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return new Constant(c, Type.getColor(), token.image);}
    throw new Error("Missing return statement in function");
}

  final public String Name() throws ParseException {Token name;
    name = jj_consume_token(IDENTIFIER);
{if ("" != null) return name.image;}
    throw new Error("Missing return statement in function");
}

  final public Type Type() throws ParseException {Token type;
    type = jj_consume_token(IDENTIFIER);
{if ("" != null) return program.getTypeByName(type.image);}
    throw new Error("Missing return statement in function");
}

  final public File File() throws ParseException {String filename;
    filename = TextRaw();
File file = new File(filename);
     if (!file.exists()) {
       file = new File(path + File.separator + filename);
     }
     {if ("" != null) return file;}
    throw new Error("Missing return statement in function");
}

  final public Constant Text() throws ParseException {String text;
    text = TextRaw();
{if ("" != null) return new Constant(text, Type.getString(), token.image);}
    throw new Error("Missing return statement in function");
}

  final public String TextRaw() throws ParseException {Token t; String text;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case STRING_LITERAL1:{
      t = jj_consume_token(STRING_LITERAL1);
      break;
      }
    case STRING_LITERAL2:{
      t = jj_consume_token(STRING_LITERAL2);
      break;
      }
    default:
      jj_la1[51] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
text = t.image;
    text = text.replace("\\n", "\n")
      .replace("\\t", "\t")
      .replace("\\n", "\n")
      .replace("\\r", "\r")
      .replace("\\\'", "\'")
      .replace("\\\\", "\\");
    {if ("" != null) return text.substring(1, text.length() - 1);}
    throw new Error("Missing return statement in function");
}

  final public Constant IntNumber() throws ParseException {Token number;
    number = jj_consume_token(INTEGER_LITERAL);
try {
        {if ("" != null) return new Constant(Integer.valueOf(number.image), Type.getInteger(), number.image);}
      } catch (NumberFormatException nfe) {
                        {if (true) throw new NumberFormatException(number.image);}
      }
    throw new Error("Missing return statement in function");
}

  final public Constant DoubleNumber() throws ParseException {Token number;
    number = jj_consume_token(FLOATING_POINT_LITERAL);
{if ("" != null) return new Constant(Double.valueOf(number.image), Type.getDouble(), number.image);}
    throw new Error("Missing return statement in function");
}

  private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_3()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_4()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_5()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_6()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_7()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_3R_AdditiveExpression_752_5_46()
 {
    if (jj_scan_token(MINUS)) return true;
    if (jj_3R_MultiplicativeExpression_763_3_37()) return true;
    return false;
  }

  private boolean jj_3R_AdditiveExpression_751_5_38()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_AdditiveExpression_751_5_45()) {
    jj_scanpos = xsp;
    if (jj_3R_AdditiveExpression_752_5_46()) return true;
    }
    return false;
  }

  private boolean jj_3R_AdditiveExpression_751_5_45()
 {
    if (jj_scan_token(PLUS)) return true;
    if (jj_3R_MultiplicativeExpression_763_3_37()) return true;
    return false;
  }

  private boolean jj_3R_Name_943_3_22()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_AdditiveExpression_750_3_33()
 {
    if (jj_3R_MultiplicativeExpression_763_3_37()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_AdditiveExpression_751_5_38()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_null_475_81_16()
 {
    if (jj_3R_Name_943_3_22()) return true;
    return false;
  }

  private boolean jj_3R_RelationalExpression_739_5_42()
 {
    if (jj_scan_token(GE)) return true;
    if (jj_3R_AdditiveExpression_750_3_33()) return true;
    return false;
  }

  private boolean jj_3R_RelationalExpression_738_5_41()
 {
    if (jj_scan_token(LE)) return true;
    if (jj_3R_AdditiveExpression_750_3_33()) return true;
    return false;
  }

  private boolean jj_3R_RelationalExpression_737_5_40()
 {
    if (jj_scan_token(GT)) return true;
    if (jj_3R_AdditiveExpression_750_3_33()) return true;
    return false;
  }

  private boolean jj_3R_RelationalExpression_736_5_39()
 {
    if (jj_scan_token(LT)) return true;
    if (jj_3R_AdditiveExpression_750_3_33()) return true;
    return false;
  }

  private boolean jj_3R_RelationalExpression_736_5_34()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_RelationalExpression_736_5_39()) {
    jj_scanpos = xsp;
    if (jj_3R_RelationalExpression_737_5_40()) {
    jj_scanpos = xsp;
    if (jj_3R_RelationalExpression_738_5_41()) {
    jj_scanpos = xsp;
    if (jj_3R_RelationalExpression_739_5_42()) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3R_RelationalExpression_735_3_31()
 {
    if (jj_3R_AdditiveExpression_750_3_33()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_RelationalExpression_736_5_34()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_ColorLiteral_925_3_82()
 {
    if (jj_scan_token(COLOR_LITERAL_RGBA)) return true;
    return false;
  }

  private boolean jj_3R_ColorLiteral_917_3_81()
 {
    if (jj_scan_token(COLOR_LITERAL_RGB)) return true;
    return false;
  }

  private boolean jj_3R_EqualityExpression_724_5_36()
 {
    if (jj_scan_token(NE)) return true;
    if (jj_3R_RelationalExpression_735_3_31()) return true;
    return false;
  }

  private boolean jj_3R_EqualityExpression_723_5_35()
 {
    if (jj_scan_token(EQ)) return true;
    if (jj_3R_RelationalExpression_735_3_31()) return true;
    return false;
  }

  private boolean jj_3R_EqualityExpression_723_5_32()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_EqualityExpression_723_5_35()) {
    jj_scanpos = xsp;
    if (jj_3R_EqualityExpression_724_5_36()) return true;
    }
    return false;
  }

  private boolean jj_3R_ColorLiteral_916_3_75()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_ColorLiteral_917_3_81()) {
    jj_scanpos = xsp;
    if (jj_3R_ColorLiteral_925_3_82()) return true;
    }
    return false;
  }

  private boolean jj_3R_EqualityExpression_722_3_27()
 {
    if (jj_3R_RelationalExpression_735_3_31()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_EqualityExpression_723_5_32()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_BooleanLiteral_910_3_80()
 {
    if (jj_scan_token(FALSE)) return true;
    return false;
  }

  private boolean jj_3R_BooleanLiteral_909_3_79()
 {
    if (jj_scan_token(TRUE)) return true;
    return false;
  }

  private boolean jj_3R_BooleanLiteral_909_3_74()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_BooleanLiteral_909_3_79()) {
    jj_scanpos = xsp;
    if (jj_3R_BooleanLiteral_910_3_80()) return true;
    }
    return false;
  }

  private boolean jj_3R_AndExpression_711_5_28()
 {
    if (jj_scan_token(AND)) return true;
    if (jj_3R_EqualityExpression_722_3_27()) return true;
    return false;
  }

  private boolean jj_3R_AndExpression_710_3_20()
 {
    if (jj_3R_EqualityExpression_722_3_27()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_AndExpression_711_5_28()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_PropertyRead_835_68_69()
 {
    if (jj_scan_token(SELF)) return true;
    return false;
  }

  private boolean jj_3R_Literal_898_3_66()
 {
    if (jj_3R_ColorLiteral_916_3_75()) return true;
    return false;
  }

  private boolean jj_3R_Literal_897_3_65()
 {
    if (jj_3R_BooleanLiteral_909_3_74()) return true;
    return false;
  }

  private boolean jj_3R_Literal_896_3_64()
 {
    if (jj_3R_Text_970_3_73()) return true;
    return false;
  }

  private boolean jj_3R_Literal_895_3_63()
 {
    if (jj_3R_DoubleNumber_1009_3_72()) return true;
    return false;
  }

  private boolean jj_3R_Literal_894_3_62()
 {
    if (jj_3R_IntNumber_996_3_71()) return true;
    return false;
  }

  private boolean jj_3R_Literal_893_3_59()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Literal_894_3_62()) {
    jj_scanpos = xsp;
    if (jj_3R_Literal_895_3_63()) {
    jj_scanpos = xsp;
    if (jj_3R_Literal_896_3_64()) {
    jj_scanpos = xsp;
    if (jj_3R_Literal_897_3_65()) {
    jj_scanpos = xsp;
    if (jj_3R_Literal_898_3_66()) return true;
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_Expression_699_5_21()
 {
    if (jj_scan_token(OR)) return true;
    if (jj_3R_AndExpression_710_3_20()) return true;
    return false;
  }

  private boolean jj_3R_Expression_698_3_15()
 {
    if (jj_3R_AndExpression_710_3_20()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_Expression_699_5_21()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_Arguments_882_9_83()
 {
    if (jj_scan_token(SEPARATOR)) return true;
    if (jj_3R_Expression_698_3_15()) return true;
    return false;
  }

  private boolean jj_3R_Arguments_880_7_76()
 {
    if (jj_3R_Expression_698_3_15()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_Arguments_882_9_83()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_AssignmentOperator_692_3_26()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(41)) {
    jj_scanpos = xsp;
    if (jj_scan_token(38)) return true;
    }
    return false;
  }

  private boolean jj_3R_Arguments_878_3_24()
 {
    if (jj_scan_token(LPAREN)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Arguments_880_7_76()) jj_scanpos = xsp;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_Assignment_683_3_19()
 {
    if (jj_3R_PropertyWrite_848_3_25()) return true;
    if (jj_3R_AssignmentOperator_692_3_26()) return true;
    return false;
  }

  private boolean jj_3_2()
 {
    if (jj_3R_Expression_698_3_15()) return true;
    if (jj_scan_token(TIMES)) return true;
    return false;
  }

  private boolean jj_3_1()
 {
    if (jj_scan_token(WHILE)) return true;
    if (jj_3R_Expression_698_3_15()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(13)) {
    jj_scanpos = xsp;
    if (jj_scan_token(24)) {
    jj_scanpos = xsp;
    if (jj_scan_token(9)) {
    jj_scanpos = xsp;
    if (jj_3R_null_475_81_16()) {
    jj_scanpos = xsp;
    if (jj_scan_token(29)) {
    jj_scanpos = xsp;
    if (jj_scan_token(23)) {
    jj_scanpos = xsp;
    if (jj_scan_token(14)) {
    jj_scanpos = xsp;
    if (jj_scan_token(18)) return true;
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_PropertyWrite_848_20_30()
 {
    if (jj_scan_token(RESULT)) return true;
    return false;
  }

  private boolean jj_3R_Function_863_3_18()
 {
    if (jj_3R_Name_943_3_22()) return true;
    if (jj_3R_Arguments_878_3_24()) return true;
    return false;
  }

  private boolean jj_3R_PropertyRead_835_20_68()
 {
    if (jj_scan_token(RESULT)) return true;
    return false;
  }

  private boolean jj_3_5()
 {
    if (jj_3R_Assignment_683_3_19()) return true;
    return false;
  }

  private boolean jj_3R_PropertyWrite_848_4_29()
 {
    if (jj_3R_Name_943_3_22()) return true;
    return false;
  }

  private boolean jj_3R_PropertyWrite_848_3_25()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_PropertyWrite_848_4_29()) {
    jj_scanpos = xsp;
    if (jj_3R_PropertyWrite_848_20_30()) return true;
    }
    return false;
  }

  private boolean jj_3_4()
 {
    if (jj_3R_Function_863_3_18()) return true;
    return false;
  }

  private boolean jj_3R_PropertyRead_835_4_67()
 {
    if (jj_3R_Name_943_3_22()) return true;
    return false;
  }

  private boolean jj_3R_PropertyRead_835_3_60()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_PropertyRead_835_4_67()) {
    jj_scanpos = xsp;
    if (jj_3R_PropertyRead_835_20_68()) {
    jj_scanpos = xsp;
    if (jj_3R_PropertyRead_835_68_69()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_Declaration_642_4_23()
 {
    if (jj_scan_token(SEPARATOR)) return true;
    return false;
  }

  private boolean jj_3R_Declaration_641_3_17()
 {
    if (jj_3R_Name_943_3_22()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_Declaration_642_4_23()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(COLON)) return true;
    return false;
  }

  private boolean jj_3R_Pow_791_36_54()
 {
    if (jj_scan_token(POW)) return true;
    if (jj_3R_Pow_790_3_52()) return true;
    return false;
  }

  private boolean jj_3R_PostPrimaryExpression_821_5_77()
 {
    if (jj_3R_PropertyRead_835_3_60()) return true;
    return false;
  }

  private boolean jj_3_7()
 {
    if (jj_3R_Function_863_3_18()) return true;
    return false;
  }

  private boolean jj_3R_PostPrimaryExpression_818_3_70()
 {
    if (jj_scan_token(DOT)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_7()) {
    jj_scanpos = xsp;
    if (jj_3R_PostPrimaryExpression_821_5_77()) return true;
    }
    return false;
  }

  private boolean jj_3R_DoubleNumber_1009_3_72()
 {
    if (jj_scan_token(FLOATING_POINT_LITERAL)) return true;
    return false;
  }

  private boolean jj_3R_PostPrimaryExpression_817_3_61()
 {
    Token xsp;
    if (jj_3R_PostPrimaryExpression_818_3_70()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_PostPrimaryExpression_818_3_70()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_PrimaryExpression_808_4_58()
 {
    if (jj_3R_PostPrimaryExpression_817_3_61()) return true;
    return false;
  }

  private boolean jj_3R_PrimaryExpression_806_5_57()
 {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_Expression_698_3_15()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_PrimaryExpression_805_5_56()
 {
    if (jj_3R_PropertyRead_835_3_60()) return true;
    return false;
  }

  private boolean jj_3_6()
 {
    if (jj_3R_Function_863_3_18()) return true;
    return false;
  }

  private boolean jj_3R_PrimaryExpression_803_5_55()
 {
    if (jj_3R_Literal_893_3_59()) return true;
    return false;
  }

  private boolean jj_3R_IntNumber_996_3_71()
 {
    if (jj_scan_token(INTEGER_LITERAL)) return true;
    return false;
  }

  private boolean jj_3_3()
 {
    if (jj_3R_Declaration_641_3_17()) return true;
    return false;
  }

  private boolean jj_3R_PrimaryExpression_802_3_53()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_PrimaryExpression_803_5_55()) {
    jj_scanpos = xsp;
    if (jj_3_6()) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_805_5_56()) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_806_5_57()) return true;
    }
    }
    }
    xsp = jj_scanpos;
    if (jj_3R_PrimaryExpression_808_4_58()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_Pow_790_3_52()
 {
    if (jj_3R_PrimaryExpression_802_3_53()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Pow_791_36_54()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_TextRaw_978_3_78()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(66)) {
    jj_scanpos = xsp;
    if (jj_scan_token(67)) return true;
    }
    return false;
  }

  private boolean jj_3R_UnaryExpression_779_3_49()
 {
    if (jj_3R_Pow_790_3_52()) return true;
    return false;
  }

  private boolean jj_3R_Text_970_3_73()
 {
    if (jj_3R_TextRaw_978_3_78()) return true;
    return false;
  }

  private boolean jj_3R_UnaryExpression_778_3_48()
 {
    if (jj_scan_token(NOT)) return true;
    if (jj_3R_Pow_790_3_52()) return true;
    return false;
  }

  private boolean jj_3R_UnaryExpression_777_3_47()
 {
    if (jj_scan_token(MINUS)) return true;
    if (jj_3R_Pow_790_3_52()) return true;
    return false;
  }

  private boolean jj_3R_UnaryExpression_776_3_43()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_UnaryExpression_777_3_47()) {
    jj_scanpos = xsp;
    if (jj_3R_UnaryExpression_778_3_48()) {
    jj_scanpos = xsp;
    if (jj_3R_UnaryExpression_779_3_49()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_MultiplicativeExpression_765_5_51()
 {
    if (jj_scan_token(DIV)) return true;
    if (jj_3R_UnaryExpression_776_3_43()) return true;
    return false;
  }

  private boolean jj_3R_MultiplicativeExpression_764_5_44()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_MultiplicativeExpression_764_5_50()) {
    jj_scanpos = xsp;
    if (jj_3R_MultiplicativeExpression_765_5_51()) return true;
    }
    return false;
  }

  private boolean jj_3R_MultiplicativeExpression_764_5_50()
 {
    if (jj_scan_token(MULT)) return true;
    if (jj_3R_UnaryExpression_776_3_43()) return true;
    return false;
  }

  private boolean jj_3R_MultiplicativeExpression_763_3_37()
 {
    if (jj_3R_UnaryExpression_776_3_43()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_MultiplicativeExpression_764_5_44()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  /** Generated Token Manager. */
  public ParserTokenManager token_source;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[52];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	   jj_la1_init_2();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x1000aa,0x1000aa,0x0,0x0,0x200000,0x80,0x80,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0xe1844200,0xe1844200,0x1800,0xe1846200,0x1000200,0x10000,0xe0800000,0x0,0x0,0x20800000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x38800000,0x0,0x18000000,0x20800000,0x0,0x20800000,0x0,0x20800000,0x20000000,0x0,0x38800000,0x18000000,0x18000000,0x0,0x0,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x0,0x0,0x1,0x8,0x0,0x0,0x0,0x1,0x8,0x10,0x1,0x8,0x10,0x0,0x10,0x10,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x10,0x20,0x0,0x240,0x2000,0x4000,0x1200,0x1200,0xd80,0xd80,0x30000,0x30000,0xc0000,0xc0000,0x40028001,0x100000,0x40000000,0x1,0x20,0x0,0x20,0x0,0x0,0x10,0x40028001,0x40000000,0x0,0x0,0x0,};
	}
	private static void jj_la1_init_2() {
	   jj_la1_2 = new int[] {0x0,0x0,0x0,0x0,0x0,0x40,0x40,0x0,0x0,0x0,0x0,0x0,0x0,0x40,0x0,0x0,0x40,0x40,0x0,0x40,0x0,0x0,0x40,0x0,0x0,0x40,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x7d,0x0,0x3d,0x40,0x0,0x40,0x0,0x40,0x40,0x0,0x7d,0x3d,0x0,0x30,0xc,};
	}
  final private JJCalls[] jj_2_rtns = new JJCalls[7];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with user supplied CharStream. */
  public Parser(CharStream stream) {
	 token_source = new ParserTokenManager(stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 52; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(CharStream stream) {
	 token_source.ReInit(stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 52; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Parser(ParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 52; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(ParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 52; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[73];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 52; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		   if ((jj_la1_2[i] & (1<<j)) != 0) {
			 la1tokens[64+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 73; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 7; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			   case 2: jj_3_3(); break;
			   case 3: jj_3_4(); break;
			   case 4: jj_3_5(); break;
			   case 5: jj_3_6(); break;
			   case 6: jj_3_7(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

}
